local banner = {
  "                                         ███╗░░██╗██╗██╗░░██╗░█████╗░██╗░░░░░░█████╗░██╗░░░██╗██╗███╗░░░███╗                                   ",
  "                                         ████╗░██║██║██║░██╔╝██╔══██╗██║░░░░░██╔══██╗██║░░░██║██║████╗░████║                                   ",
  "                                         ██╔██╗██║██║█████═╝░██║░░██║██║░░░░░███████║╚██╗░██╔╝██║██╔████╔██║                                   ",
  "                                         ██║╚████║██║██╔═██╗░██║░░██║██║░░░░░██╔══██║░╚████╔╝░██║██║╚██╔╝██║                                   ",
  "                                         ██║░╚███║██║██║░╚██╗╚█████╔╝███████╗██║░░██║░░╚██╔╝░░██║██║░╚═╝░██║                                   ",
  "                                         ╚═╝░░╚══╝╚═╝╚═╝░░╚═╝░╚════╝░╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝                                   ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
  "                                                               ................                                                                ",
  "                                                          .......''''''''''''.......                                                           ",
  "                                                      .....',,;;::cccccccc:::;,,''......                                                       ",
  "                                                   ....',;::cloollcc::::;;::::cc::;,'......                                                    ",
  "                                                 ....,;:cloolc:;;;,,,,,,,''''''',;:::;,'.....                                                  ",
  "                                               ...',;clodoc:;;;::::;,,,,'',,,,''...',;:;,'.....                                                ",
  "                                             ....,;clodl::::cc:;'...        ....'''...';:;,......                                              ",
  "                                          .....';clodoc:cccc;'.                  ........,;;'.....                                             ",
  "                                        ......,:lodol:clcc:'                        ......';;,......                                           ",
  "                                     .......';coddoccllcc;.                          .......,;,'.......                                        ",
  "                                .........',:cooooocllccc,                              ..'...',,'.........                                     ",
  "                        .........'''',,;:loooooddoolccl,                                ..''....'''...........                                 ",
  "                  ........',;;:::::ccllooooolodxddolcc'                                  ....'.........................                        ",
  "            ........'',;::cloollllllldddxxxkdddxdol:;,.                                     ........''.....................                    ",
  "               .........'',,;;;:::c:ccloooooooooollccc::;;;,,'''....................................''.................                        ",
  "                              ..............''''.''...''''''''''''''''''''''............................                                       ",
  "                                                                                                                                               ",
  "                                                    .......                            ...                                                     ",
  "                                                   .':l::lc.                       ....,;..                                                    ",
  "                                                   ..,cl:;cc;.                   ....',;'..                                                    ",
  "                                                    ..,:lc;;:c;'..            ...'.',;;'..                                                     ",
  "                                                     ..';clc:;;;:;;,''.....'''''',,;;,..                                                       ",
  "                                                       ..';:ccc::;;,,,,,,,,,,,;;;:;'...                                                        ",
  "                                                         ...',;:cccc::::::::::;;'....                                                          ",
  "                                                             ....'',,,,,,,,'.....                                                              ",
  "                                                                  ..........                                                                   ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
  "                                                                                                                                               ",
}

return {
  "snacks.nvim",
  opts = {
    dashboard = {
      preset = {
        pick = function(cmd, opts)
          return LazyVim.pick(cmd, opts)()
        end,
        header = "\n" .. table.concat(banner, "\n") .. "\n",
        -- stylua: ignore
        ---@type snacks.dashboard.Item[]
        keys = {
          { icon = " ", key = "f", desc = "Find File", action = ":lua Snacks.dashboard.pick('files')" },
          { icon = " ", key = "n", desc = "New File", action = ":ene | startinsert" },
          { icon = " ", key = "g", desc = "Find Text", action = ":lua Snacks.dashboard.pick('live_grep')" },
          { icon = " ", key = "r", desc = "Recent Files", action = ":lua Snacks.dashboard.pick('oldfiles')" },
          { icon = " ", key = "c", desc = "Config", action = ":lua Snacks.dashboard.pick('files', {cwd = vim.fn.stdpath('config')})" },
          { icon = " ", key = "s", desc = "Restore Session", section = "session" },
          { icon = " ", key = "x", desc = "Lazy Extras", action = ":LazyExtras" },
          { icon = "󰒲 ", key = "l", desc = "Lazy", action = ":Lazy" },
          { icon = " ", key = "q", desc = "Quit", action = ":qa" },
        },
      },
    },
  },
}
